name: Steps View (action)
on:
  - workflow_dispatch

jobs:
  custom-job:
    runs-on: ubuntu-latest
    steps:
      - id: jaspal
        run: |
          echo "firstName=aman" >> $GITHUB_OUTPUT
          echo "middleName=jaspal" >> $GITHUB_OUTPUT
          echo "lastName=singh" >> $GITHUB_OUTPUT

      - run: echo "First name is ${{steps.jaspal.outputs.firstName}}"
      - run: echo "Middle name is ${{steps.jaspal.outputs.middleName}}"
      - run: echo "LastName name is ${{steps.jaspal.outputs.lastName}}"
